#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

# Check if the correct number of arguments is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variable s
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# transfer the file to the server
scp -o stricthostkeychecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip":~/
