#!/usr/bin/env bash
# this script configures nginx to return a custom 404 page.

# create a custom 404 page
echo "ceci n'est pas une page" > /var/www/html/404.html

# modify the nginx configuration to use the custom 404 page
cat > /etc/nginx/sites-available/custom_404 <<eof
server {
    listen 80;
    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
eof

# enable the new configuration
ln -sf /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# test the nginx configuration
nginx -t

# restart nginx to apply the changes
service nginx restart
