#!/usr/bin/env bash
# Install and configure HAProxy on your load balancer server (lb-01).

# Install necessary software properties for adding repositories
apt-get install -y software-properties-common

# Add the HAProxy PPA for version 1.8
add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update package lists
apt-get update

# Install HAProxy version 1.8
apt-get install -y haproxy=1.8.*

# Define the HAProxy configuration for the load balancer
load_balancer="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b

backend load_b\n
\tbalance roundrobin
\tserver web-01 54.164.253.166:80 check
\tserver web-02 52.204.144.35:80 check
"

# Enable HAProxy service
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy

# Append the load balancer configuration to the HAProxy config file
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart the HAProxy service to apply changes
service haproxy restart
