#!/usr/bin/env bash
# Init script to manage manage_my_process

PIDFILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start() {
    # Start the process
    $SCRIPT &
    echo $! > $PIDFILE
    echo "manage_my_process started"
}

stop() {
    # Stop the process
    if [ -f "$PIDFILE" ]; then
        pid=$(cat $PIDFILE)
        kill $pid
        rm $PIDFILE
    fi
    echo "manage_my_process stopped"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
