#!/usr/bin/env bash
# Init script to manage manage_my_process daemon
# Usage: manage_my_process {start|stop|restart}

PIDFILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

# Function to start the process
start_process()
{
    $SCRIPT &
    echo "$!" > "$PIDFILE"
    echo "manage_my_process started"
}

# Function to stop the process
stop_process()
{
    if [ -e "$PIDFILE" ]
    then
        pid=$(cat "$PIDFILE")
        kill "$pid"
        rm "$PIDFILE"
    fi
    echo "manage_my_process stopped"
}

# Main case statement for command handling
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        stop_process
        start_process
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
