#!/usr/bin/env bash
# This script displays text indefinitely with a sleep 2 and handles SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
