#!/usr/bin/env bash
# 101-tell_the_story_of_passwd
# Script that displays the content of /etc/passwd using IFS and while loop
# Format: The user USERNAME is part of the GROUP_ID gang...

while IFS=':' read -r username password uid gid info home shell
do
    echo "The user $username is part of the $gid gang,\
 lives in $home and rides $shell. $uid's place is protected by the passcode\
 $password, more info about the user here: $info"
done < "/etc/passwd"
