#!/usr/bin/env bash
# Displays the content of current directory in list format
# Only displays the part of the name after the first dash

for file in *
do
    if [[ $file != .* ]]  # Skip hidden files
    then
        echo "$file" | cut -d'-' -f2-
    fi
done
