#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine

# Using ip command (modern approach)
ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}'

# Alternative using ifconfig (traditional approach)
# ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | cut -b 11-
